## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [9]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])
media_salario = np.mean(salarios)
print (media_salario)
print(np.where(salarios > media_salario,))
print(salarios[salarios > media_salario])
print(salarios > media_salario)
print(np.sum(salarios > media_salario)) # SOMA OS ITENS QUE SÃO TRUE
# ISSO FUNCIONA PQ VALORES TRUE É 1 E VALORES FALSE É 0
print(True == 1)
print(False == 0)
print(sum([True, False, True, False]))


3455.5555555555557
(array([2, 3, 5, 7, 8], dtype=int64),)
[3500 4000 4500 3800 4800]
[False False  True  True False  True False  True  True]
5
True
True
2


In [10]:
func_acima_media = np.sum(salarios > media_salario)
print(f"A quantidade de funcionários com salário acima da média é: {func_acima_media}")

A quantidade de funcionários com salário acima da média é: 5


In [14]:
print(np.count_nonzero(salarios > media_salario))
print(np.unique(salarios > media_salario))
print(np.unique(salarios > media_salario, return_counts=True))
valores_unicos, contagem = np.unique(salarios > media_salario, return_counts=True)
print (valores_unicos)
print (contagem)

5
[False  True]
(array([False,  True]), array([4, 5], dtype=int64))
[False  True]
[4 5]


In [19]:
# CRIANDO 20 VALORES FICTICIOS DE SALARIOS COM A MESMA FAIXA ANTERIOR, TOMANDO CUIDADO DE OUTRAS PESSOAS GERAREM OS MESMOS VALORES
rng = np.random.default_rng(seed=42)
# SEM ENDPOINT 
salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20)
print(salarios_gerados)
salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20, endpoint=True)
print(salarios_gerados)
print(np.mean(salarios_gerados))
print(salarios_gerados.mean())
print(salarios_gerados.max())
print(salarios_gerados.min())

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]
[3401 3038 2511 4595 4189 3803 3127 4304 3527 3242 3261 2636 2258 3553
 4486 2178 4404 4318 2775 3769]
3468.75
3468.75
4595
2178
